version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - '8080:8080'
      - '7331:7331'
    volumes:
      - .:/usr/app
    extends:
      file: docker-compose.yml
      service: go-app

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

volumes:
  redis-data:
  postgres-data:

networks:
  app-network:
