version: '3.8'

services:
  go-app:
    build: .
    container_name: go_server
    ports:
      - '8080:8080'
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis:6379
      - REDIS_USERNAME=redis
      - REDIS_PASSWORD=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gorssagg
    networks:
      - app-network

  redis:
    container_name: redis_cache
    build:
      context: ./services/redis
      dockerfile: dockerfile
    ports:
      - '6379:6379'
    environment:
      - REDIS_USERNAME=redis
      - REDIS_PASSWORD=redis
      - REDIS_DISABLE_DEFAULT_USER=true
    volumes:
      - redis-data:/data
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gorssagg
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  redis-data:
  postgres-data:

networks:
  app-network:
